# Generated by Django 3.2.23 on 2026-02-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='地址'),
        ),
    ]
