# Generated by Django 3.2.23 on 2026-02-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_review_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
