# Generated by Django 3.2.23 on 2026-02-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='食堂图片'),
        ),
    ]
