# Generated by Django 3.2.23 on 2026-02-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='title',
        ),
    ]
