# Generated by Django 3.2.23 on 2026-03-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0008_remove_carousel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='访问次数'),
        ),
    ]
