# Generated by Django 3.2.23 on 2026-03-19 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_app', '0010_review_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reply', '评论回复'), ('system', '系统通知'), ('other', '其他通知')], max_length=20, verbose_name='通知类型')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('related_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_app.review', verbose_name='相关评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '通知信息',
                'verbose_name_plural': '通知信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
